### ISSUE TITLE
FP32 vs FP64

### ISSUE THREAD

**Issue by rickyzhang82** [cavazos-lab/FinanceBench#1]
For benchmark purpose, could you parameterize the type of floating point calculation? Some test mixed with them. 

It would be great that if it can separate run in either FP32 or FP64.

**Comment by willkill07** [comment]
No. Bonds and Repo require 64-bit precision while Black Scholes and Monte Carlo only need 32-bit. Adjusting precision in benchmarks are useful if it's a synthetic benchmark, but these applications are supposed to be realistic in terms of industry-deployed computations.
